apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  labels:
    name: docker-registry
spec:
  ports: 
  - targetPort: 5000
    port: $registry_port 
    nodePort: $node_port
  type: NodePort
  selector:
    app: docker-registry
