apiVersion: v1
kind: Pod
metadata:
  name: docker-registry
  labels:
    name: docker-registry
    app: docker-registry
spec:
  containers:
  - name: registry
    image: $registry_image
    env:
    - name: REGISTRY_PROXY_REMOTEURL
      value: $registry_proxy_remoteurl
    ports:
    - name: registry-port
      containerPort: 5000
    volumeMounts:
    - name: registry-storage
      mountPath: /var/lib/registry
    securityContext:
      runAsUser: $docker_user
  volumes:
  - name: registry-storage
    hostPath: 
      path: $registry_host_dir
